### ISSUE TITLE
State update error

### ISSUE THREAD

**Issue by stalkerj** [wiistriker/homebridge-terneo-heatfloor#1]
Please help me with error in 1 of 3 terneo termostat. Local API was enabled.

[2/20/2020, 9:48:24 AM] [Теплый пол - ванна] [Terneo] [DEBUG] Begin state update
[2/20/2020, 9:48:24 AM] [Теплый пол - ванна] [Terneo] [DEBUG] Begin state update
[2/20/2020, 9:48:30 AM] [Теплый пол - ванна] [Terneo] [WARNING] State update error Error: Response has no telemetry data
    at axios.post.then (/homebridge/node_modules/homebridge-terneo-heatfloor/index.js:104:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)

[2/20/2020, 9:48:30 AM] [Теплый пол - ванна] [Terneo] [WARNING] State update error Error: Response has no telemetry data
    at axios.post.then (/homebridge/node_modules/homebridge-terneo-heatfloor/index.js:104:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)

[2/20/2020, 9:48:30 AM] [Теплый пол - ванна] [Terneo] [DEBUG] Schedule new state update after 60 sec.
[2/20/2020, 9:48:30 AM] [Теплый пол - ванна] [Terneo] [DEBUG] Schedule new state update after 60 sec.
[2/20/2020, 9:49:30 AM] [Теплый пол - ванна] [Terneo] [DEBUG] Begin state update
[2/20/2020, 9:49:30 AM] [Теплый пол - ванна] [Terneo] [DEBUG] Begin state update
[2/20/2020, 9:49:35 AM] [Теплый пол - ванна] [Terneo] [WARNING] State update error Error: Response has no telemetry data
    at axios.post.then (/homebridge/node_modules/homebridge-terneo-heatfloor/index.js:104:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)

[2/20/2020, 9:49:35 AM] [Теплый пол - ванна] [Terneo] [WARNING] State update error Error: Response has no telemetry data
    at axios.post.then (/homebridge/node_modules/homebridge-terneo-heatfloor/index.js:104:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by wiistriker** [comment]
Please show me your config files with accessories (you can delete ip, serial numbers and other sensitive information). Do you have only one accessory or more? What terneo device do you have?

It looks little bit confusing that all messages in logs doubled

**Comment by stalkerj** [comment]
Messages is going from time to time only about 1 thermostat.
Here my config for terneo. I have 3 thermostats.

{
            "accessory": "TerneoHeatfloor",
            "name": "Теплый пол - кухня",
            "ip": "10.0.1.191",
            "serial": "0C0017000B4xxxxxxxxxxxxxxxxxx"
        },
        {
            "accessory": "TerneoHeatfloor",
            "name": "Теплый пол - гостинная",
            "ip": "10.0.1.251",
            "serial": "0F000D00094xxxxxxxxxxxxxxxxxxx"
        },
        {
            "accessory": "TerneoHeatfloor",
            "name": "Теплый пол - ванна",
            "ip": "10.0.1.250",
            "serial": "1D000A00024xxxxxxxxxxxxxxxxxxxxxxxxxx"
        },

**Comment by stalkerj** [comment]
![Снимок](https://user-images.githubusercontent.com/17808225/74931297-63cf2e00-53f0-11ea-87cb-ecd8daaec241.PNG)

**Comment by wiistriker** [comment]
Could you please check with one thermostat?

**Comment by stalkerj** [comment]
Should I delete thermostats that works fine from config?

**Comment by wiistriker** [comment]
So only one thermostat not working correctly? Another two working fine?
Could you please check blocking parameter again and maybe restart not working device? Can you power off not working device?

**Comment by stalkerj** [comment]
Only one thermostat gave an error in log. blc - off - i checked it few times already.

**Comment by stalkerj** [comment]
I think that i found a problem. Thermostat that make error has firmware 2.3 (jay test), otherone has 2.3 (jay). I initiate updating.

**Comment by wiistriker** [comment]
Did the update help?

**Comment by stalkerj** [comment]
Yes it is

**Comment by mksmo** [comment]
> I think that i found a problem. Thermostat that make error has firmware 2.3 (jay test), otherone has 2.3 (jay). I initiate updating.

Hi,
How did you initiated update? I've got firmware v 2.3 (jay test), and there is no updates available.
Thanks

**Comment by stalkerj** [comment]
Я думал что смог это сделать, но нет. У меня была кнопка обновления в веб интерфейсе, я ее надал но прошивка не изменилась. Ошибка вылезает иногда, но чаще ее нет

**Comment by mksmo** [comment]
> У меня была кнопка обновления в веб интерфейсе, я ее надал но прошивка не изменилась.

В поддержке Terneo сообщили о выходе обновления через 2 недели.

**Comment by wiistriker** [comment]
Выкатил версию 1.0.4, обновитесь, посмотрите на поведение

**Comment by denyslietnikov** [comment]
> 
> 
> Выкатил версию 1.0.4, обновитесь, посмотрите на поведение

На последней версии все равно есть ошибка регулярная в логе:

[11/25/2020, 06:02:17] [Теплый пол Ванная] [Terneo] [WARNING] State update error Error: Response has no parameters data
    at /usr/local/lib/node_modules/homebridge-terneo-heatfloor/index.js:209:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[11/25/2020, 06:05:19] [Теплый пол Ванная] [Terneo] [WARNING] State update error Error: Response has no parameters data
    at /usr/local/lib/node_modules/homebridge-terneo-heatfloor/index.js:209:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by akaGDM** [comment]
Ошибка появляется на устройстве, которое записано последним в конфиге. Если убрать из конфига ванную, то ошибка будет на гостиной в случае топикстартера. У меня такая закономерность

**Comment by snappytoes1** [comment]
Аналогичная ошибка. Все еще нет решения?

**Comment by wiistriker** [comment]
Про какую версию прошивки речь?

**Comment by wiistriker** [comment]
поправил ошибку, при котором обновлялся только последний добавленный в список теплый пол. проверьте версию 1.0.6

**Comment by pero-shpak** [comment]
1.0.6 Версия

[Теплый пол] [Terneo] [WARNING] State update error Error: Response has no parameters data
    at /usr/local/lib/node_modules/homebridge-terneo-heatfloor/index.js:156:27
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[homebridge-terneo-heatfloor] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 0 exceeded minimum of 5. See https://git.io/JtMGR for more info.
 [homebridge-terneo-heatfloor] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 0 exceeded minimum of 5. See https://git.io/JtMGR for more info.
[Теплый пол] [Terneo] [WARNING] Active set failure 
 [Теплый пол] [Terneo] [WARNING] Active set failure 
[Теплый пол] [Terneo] [WARNING] Active set failure 
[Теплый пол] [Terneo] [WARNING] LockPhysicalControls set failure, reponse: 
 [Теплый пол] [Terneo] [WARNING] State update error Error: Response has no parameters data
    at /usr/local/lib/node_modules/homebridge-terneo-heatfloor/index.js:156:27
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[Теплый пол] [Terneo] [WARNING] State update error Error: Response has no parameters data
    at /usr/local/lib/node_modules/homebridge-terneo-heatfloor/index.js:156:27
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[Теплый пол] [Terneo] [WARNING] State update error Error: Response has no parameters data
    at /usr/local/lib/node_modules/homebridge-terneo-heatfloor/index.js:156:27
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by MityaSavchenko** [comment]
Есть какие-либо апдейты по этому? Также постоянно получаю эту ошибку ("Terneo] [WARNING] State update error Error: Response has no parameters data") на версии 1.0.6.
Device firmware - 2.5(raven)

**Comment by wiistriker** [comment]
Пока апдейтов никаких. Инженеры тернео говорят, что плагин часто опрашивает устройство и оно падает. Хотя частота опроса - 60 секунд.

Несколько девайсов одновременно заработало?

**Comment by akaGDM** [comment]
> Несколько девайсов одновременно заработало?

Пять штук работает. Очень редко бывает один отвалится. Управляется все из Home Kit. HB в лог частенько пишет про какую-то недопустимую характеристику, не помню точно

**Comment by snappytoes1** [comment]
Вот такая ошибка. Все еще не исправлено...

[Terneo] [WARNING] State update error [AxiosError: timeout of 3000ms exceeded] {
  code: 'ECONNABORTED',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 3000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function] },
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/0.27.2',
      'Content-Length': 9


     ........
