### ISSUE TITLE
Некорректная работа плагина в Homebridge

### ISSUE THREAD

**Issue by CasingOne** [wiistriker/homebridge-terneo-heatfloor#5]
Приветствую!
Имеется термостат Terneo SX, версия прошивки 2.5 (raven). Прокинул при помощи вашего плагина через Homebridge (версия v1.3.6) в Apple HomeKit, но поведение при управлении через HomeKit очень странное:

1. При нажатии на "плитку" термостата он выключается; включить обратно можно только кнопками на устройстве или через фирменное приложение.

2. Если зайти в настройки термостата по долгому нажатию на плитку то все данные отображаются верно: текущая температура, температура нагрева настройки и так далее. Но управлять устройством не выходит.

3. Homebridge постоянно "ругается" в логи:

[homebridge-terneo-heatfloor] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: null! Home App will reject null for Apple defined characteristics. See https://git.io/JtMGR for more info.

[Terneo] [WARNING] State update error Error: Response has no telemetry data
    at /usr/local/lib/node_modules/homebridge-terneo-heatfloor/index.js:203:43
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    
[Terneo] [WARNING] HeatingThresholdTemperature set failure, response: {...}

Если есть предположения что с этим можно сделать - буду невероятно благодарен.

**Comment by volodymyrsteblyk** [comment]
Большую часть времени регулятор на версии 2.5 **raven2** находится в состоянии "no response"

[08/12/2021, 15:15:25] [Теплый пол2] [Terneo] [WARNING] State update error Error: Response has no telemetry data
    at /usr/local/lib/node_modules/homebridge-terneo-heatfloor/index.js:203:43
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[08/12/2021, 15:15:25] [Теплый пол2] [Terneo] [DEBUG] Schedule new state update after 60 sec.
[08/12/2021, 15:15:58] [Теплый пол2] [Terneo] [DEBUG] Set Active to 0, type: number
[08/12/2021, 15:15:59] [Теплый пол2] [Terneo] [WARNING] Active set failure {
  sn: '*',
  par: [
    [ 23, 2, '9' ],        [ 114, 7, '0' ],
    [ 115, 7, '0' ],       [ 29, 1, '127' ],
    [ 0, 6, '536112000' ], [ 1, 6, '536112000' ],
    [ 2, 2, '1' ],         [ 31, 1, '24' ],
    [ 55, 2, '24' ],       [ 3, 2, '0' ],
    [ 18, 2, '2' ],        [ 19, 2, '10' ],
    [ 21, 1, '0' ],        [ 5, 1, '24' ],
    [ 7, 1, '5' ],         [ 80, 1, '0' ],
    [ 81, 1, '0' ],        [ 82, 1, '0' ],
    [ 25, 2, '15' ],       [ 26, 1, '45' ],
    [ 27, 1, '5' ],        [ 28, 2, '16' ],
    [ 17, 4, '175' ],      [ 52, 4, '1320' ],
    [ 53, 4, '480' ],      [ 117, 7, '0' ],
    [ 118, 7, '0' ],       [ 121, 7, '0' ],
    [ 124, 7, '0' ],       [ 125, 7, '1' ],
    [ 120, 7, '0' ],       [ 109, 7, '0' ]
  ]
}

**Comment by wiistriker** [comment]
Добрый день! Сообщил о проблеме инженерам terneo, жду ответа

**Comment by snappytoes1** [comment]
Аналогичные проблемы, через пару дней работы плагин ломает весь homebridge с ошибкой no response
